---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: newbie-db-dev
  namespace: cw
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
