---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: newbie-dev
    role: frontend
  name: newbie-bot-dev
  namespace: cw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newbie-dev
  template:
    metadata:
      labels:
        app: newbie-dev
        role: frontend
    spec:
      hostname: bot
      subdomain: newbie-dev
      containers:
      - image: itcw/newbie_bot:v0.2-46-g24e96ee
        imagePullPolicy: Always
        name: bot
        ports:
        - containerPort: 5000
# DEBUG: Enable these lines if you need to make the container 
#        stop terminating on failure (overrides CMD in Dockerfile)
#        command: [ "sleep" ]
#        args: [ "infinity" ]
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi
        volumeMounts:
        - mountPath: /usr/src/env
          name: env
      terminationGracePeriodSeconds: 90
      volumes:
      - name: env
        secret:
          secretName: newbie-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: newbie-dev
    role: backend
  name: newbie-db-dev
  namespace: cw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newbie-dev
  template:
    metadata:
      labels:
        app: newbie-dev
        role: backend
    spec:
      hostname: db
      subdomain: newbie-dev
      containers:
      - image: itcw/newbie_db:v0.2-dev
        imagePullPolicy: Always
        name: db
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-storage
      terminationGracePeriodSeconds: 90
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: newbie-db-dev
